version: "3.8"

services:

  api:
    build: ./
    ports:
      - '8080:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysql:3306/pruebatecnica",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pruebatecnica'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'
    volumes:
      - pruebatecnica:/var/lib/db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 100

volumes:
  pruebatecnica: